"""Core analysis primitives — language-agnostic graphs, formatters, and types."""

from .types import AnalysisResult, ModuleAnalysis
from .graphs import (
    shorten_module,
    generate_dependency_graph,
    generate_class_hierarchy,
    generate_entry_point_map,
    generate_coupling_density,
    generate_facade_leaks,
    generate_test_boundary_analysis,
    generate_init_hygiene,
    build_facade_exports,
    detect_cycles,
    find_function_calls,
    CallCollector,
)
from .formatters import (
    format_dependency_mermaid,
    format_dependency_text,
    format_class_tree_text,
    format_entry_points_text,
    format_coupling_density_text,
    format_facade_leaks_text,
    format_test_boundary_text,
    format_init_hygiene_text,
    format_cycles_text,
    format_cycles_mermaid,
    format_toon,
)

__all__ = [
    "AnalysisResult",
    "ModuleAnalysis",
    "shorten_module",
    "generate_dependency_graph",
    "generate_class_hierarchy",
    "generate_entry_point_map",
    "generate_coupling_density",
    "generate_facade_leaks",
    "generate_test_boundary_analysis",
    "generate_init_hygiene",
    "build_facade_exports",
    "detect_cycles",
    "find_function_calls",
    "CallCollector",
    "format_dependency_mermaid",
    "format_dependency_text",
    "format_class_tree_text",
    "format_entry_points_text",
    "format_coupling_density_text",
    "format_facade_leaks_text",
    "format_test_boundary_text",
    "format_init_hygiene_text",
    "format_cycles_text",
    "format_cycles_mermaid",
    "format_toon",
]
